import json
from typing import Any, Union

from requests import Response

from lowerpines.gmi import GMI


class Request:
    gmi = ... #  type: GMI
    result = ... #  type: Any
    base_url = ... #  type: str

    def __init__(self, gmi) -> None: ...
    def url(self) -> str: ...
    def mode(self) -> str: ...
    def parse(self, response: dict) -> Any: ...
    def args(self) -> dict: ...
    def execute(self) -> Union[None, json]: ...
    def error_check(self, request) -> None: ...
