from typing import List

from lowerpines import AbstractManager
from lowerpines.endpoints.group import Group


class GroupManager(AbstractManager):
    def _all(self) -> List[Group]: ...
    def former(self) -> List[Group]: ...
    def join(self, group_id: str, share_token: str) -> Group: ...
    def rejoin(self, group_id: str) -> Group: ...
