name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          PYTHONPATH=$PYTHONPATH:`pwd` coverage run -m unittest --verbose
      #          coveralls
      - name: Check Types - Pyre
        run: pyre check
      - name: Check Types - MyPy
        run: mypy .
      - name: Check Lint - Flake8
        run: flake8
      - name: Check Format - Black
        run: black --check .
      - name: Build Package
        run: python3 setup.py sdist bdist_wheel
